name: discover_printers
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  network_info_plus: ^4.0.1
#  image: ^3.0.2
  esc_pos_printer:
    path: ../../
  intl: ^0.18.0
  qr_flutter: ^4.1.0
  path_provider: ^2.0.15
#  esc_pos_utils: ^1.0.0
#  esc_pos_utils:
#    path: ../../../esc_pos_utils
  charset_converter: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/rabbit_black.jpg
    - assets/ic_clock.png
