name: esc_pos_printer
description: The library allows to print receipts using an ESC/POS thermal WiFi printer.
version: 5.0.0
homepage: https://github.com/andrey-ushakov/esc_pos_printer
publish_to: 'none'

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  esc_pos_utils:
#    path: ../esc_pos_utils
  esc_pos_utils:
    git:
      url: git@github.com:heapsapp/esc_pos_utils.git
      ref: feature/custom-printer
  charset_converter: ^2.1.1
  image: ^4.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
